image: adahlberg/nlblueprintci:18.04

.add_ssh_key: &ssh_key
    before_script:
        ## Add private key to server access
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "$SSH_PRIVATE_KEY" | ssh-add - > ~/.ssh/id_rsa
        - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        - source venv/bin/activate

.source_venv: &venv
    before_script:
        - source venv/bin/activate

stages:
    - install
    - lint
    - tests
    - examples
    - deploy

install:
    stage: install
    artifacts:
        paths:
            - venv
        expire_in: 1 hour
    before_script:
        - pip3 install virtualenv
        - virtualenv venv
        - source venv/bin/activate
    script: make install
    only:
        - master
        - merge_requests

lint:
    <<: *venv
    stage: lint
    script: make lint
    only:
        - master
        - merge_requests

test:
    <<: *venv
    stage: tests
    script: make tests
    only:
        - master
        - merge_requests

examples:
    <<: *venv
    stage: examples
    script: make examples
    only:
        - master
        - merge_requests

deploy-wheel:
    <<: *ssh_key
    stage: deploy
    only:
        - master
    when: manual
    script: make deploy-bdist

deploy-docs:
    <<: *ssh_key
    stage: deploy
    only:
        - master
    when: manual
    script: 
        - cd docs
        - make build
        - make upload
        - cd ..
